version: "3"
services:
  website:
    build:
      context: docker/production
      dockerfile: Dockerfile
    image: quay.io/log-detective/website
    hostname: log-detective
    stdin_open: true
    tty: true
    ports:
      - 8080:8080
    volumes:
      - persistent:/persistent:z

volumes:
  persistent:
